a = input('Digite algo: ')
print('O tipo primitivo desse valor é: ', type(a))
print('Só tem espaços?', a.isspace())
print('Ẽ um número?', a.isnumeric())
print('É alfabético?', a.isalpha())
print('Ẽ alfanumérico?', a.isalpha())
print('É maiúsculo?', a.isupper())
print('Ẽ minúscula?', a.islower())
print('Está capitalizada', a.istitle())